import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export type PdfLine = {
  name: string;
  quantity: number;
  price: number;
};

export type PdfDocInput = {
  title: string; // Invoice / Estimate
  fullNumber: string;
  companyName: string;
  customerName: string;
  customerEmail?: string | null;
  customerAddress?: string | null;
  dateLabel: string;
  status: string;
  subTotal: number;
  discountAmount: number;
  taxAmount: number;
  grandTotal: number;
  note?: string | null;
  lines: PdfLine[];
};

function money(n: number) {
  return `$${(n || 0).toFixed(2)}`;
}

/** Returns raw PDF bytes (Uint8Array) */
export async function buildPdfBytes(doc: PdfDocInput): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([612, 792]); // US Letter
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  let y = 750;
  const left = 50;
  const right = 562;

  const draw = (
    text: string,
    x: number,
    yy: number,
    size = 11,
    isBold = false,
  ) => {
    page.drawText(text.slice(0, 90), {
      x,
      y: yy,
      size,
      font: isBold ? bold : font,
      color: rgb(0.06, 0.09, 0.16),
    });
  };

  draw(doc.companyName || "PaySuite", left, y, 18, true);
  draw(doc.fullNumber, right - 140, y, 14, true);
  y -= 18;
  draw(doc.title, left, y, 10);
  draw(doc.dateLabel, right - 200, y, 10);
  y -= 14;
  draw(`Status: ${doc.status}`, right - 140, y, 10);
  y -= 28;

  draw("Bill to", left, y, 9);
  y -= 14;
  draw(doc.customerName, left, y, 12, true);
  y -= 14;
  if (doc.customerEmail) {
    draw(doc.customerEmail, left, y, 10);
    y -= 12;
  }
  if (doc.customerAddress) {
    draw(doc.customerAddress, left, y, 10);
    y -= 12;
  }
  y -= 16;

  // Table header
  page.drawRectangle({
    x: left,
    y: y - 4,
    width: right - left,
    height: 18,
    color: rgb(0.95, 0.97, 0.98),
  });
  draw("Item", left + 4, y, 10, true);
  draw("Qty", right - 200, y, 10, true);
  draw("Price", right - 130, y, 10, true);
  draw("Total", right - 60, y, 10, true);
  y -= 22;

  for (const line of doc.lines) {
    if (y < 120) break;
    draw(line.name || "Item", left + 4, y, 10);
    draw(String(line.quantity), right - 200, y, 10);
    draw(money(line.price), right - 130, y, 10);
    draw(money(line.quantity * line.price), right - 60, y, 10);
    y -= 16;
  }

  y -= 12;
  const totalsX = right - 180;
  draw("Subtotal", totalsX, y, 10);
  draw(money(doc.subTotal), right - 60, y, 10);
  y -= 14;
  draw("Discount", totalsX, y, 10);
  draw(`-${money(doc.discountAmount)}`, right - 60, y, 10);
  y -= 14;
  draw("Tax", totalsX, y, 10);
  draw(money(doc.taxAmount), right - 60, y, 10);
  y -= 16;
  draw("Grand total", totalsX, y, 12, true);
  draw(money(doc.grandTotal), right - 60, y, 12, true);

  if (doc.note) {
    y -= 36;
    draw("Note", left, y, 10, true);
    y -= 14;
    draw(doc.note, left, y, 10);
  }

  draw("Generated by PaySuite", left, 40, 8);

  return pdf.save();
}

export function toBase64(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString("base64");
}
