/**
 * Email template types and their shipped default bodies, carried over from the
 * Laravel installer seeders (TemplateTypeSeeder, TemplateSeeder). Subjects and
 * bodies keep the original {placeholder} tokens so existing mail rendering
 * keeps working.
 */
export const EMAIL_TEMPLATE_TYPES = [
  { name: "forget_password", displayName: "Forgot password", groupName: "password" },
  { name: "password_change_confirmation", displayName: "Password change confirmation", groupName: "password" },
  { name: "user_invitation", displayName: "User invitation", groupName: "users" },
  { name: "user_joined", displayName: "User joined", groupName: "users" },
  { name: "subscriber_register", displayName: "Subscriber register", groupName: "subscribers" },
  { name: "account_has_been_deleted", displayName: "Account has been deleted", groupName: "subscribers" },
  { name: "confirmation_of_account_deletion_request", displayName: "Confirmation of account deletion request", groupName: "subscribers" },
  { name: "invoice_sending_attachment", displayName: "Invoice Sending Attachment", groupName: "invoices" },
  { name: "payment_received", displayName: "Invoice Payment Received", groupName: "invoices" },
  { name: "estimate_sending_attachment", displayName: "Estimate Sending Attachment", groupName: "estimates" },
  { name: "subscriber_billing_information", displayName: "Subscriber Billing Information", groupName: "subscribers" },
  { name: "subscriber_expired_reminder", displayName: "Subscriber Expired Reminder", groupName: "subscribers" },
  { name: "customer_credential", displayName: "Customer invitation", groupName: "customer" },
] as const;

export const EMAIL_TEMPLATES = [
  {
    type: "user_invitation",
    subject: "You’re Invited to {app_name} – Get Started in Minutes",
    defaultContent: "<p class=\"logo\" style=\"text-align: center; width: 70%;\"><img width=\"auto\" height=\"72px\" src=\"{app_logo}\" alt=\"Logo\"/></p> <p style=\"color: #4F5867; font-size: 15px; padding-top: 20px; margin: 0 auto; width: 70%;\"> Hey, </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 30px; margin: 0 auto; width: 70%;\">Exciting news! {app_name} has invited you to join Easy Invoice, the easiest way to manage invoices,quotes, and payments.</p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 30px; margin: 0 auto; width: 70%;\">Here’s how to get started:</p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 10px; margin: 0 auto; width: 70%;\"><span>1️.</span> <strong>Activate Your Account</strong> – Click below to set up your password. </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 10px; margin: 0 auto; width: 70%;\"><span>2️.</span> <strong>Explore the Features</strong> – Create invoices, send estimates, and track payments effortlessly. </p> <p style=\"text-align: center; padding-top: 50px; padding-bottom: 50px; width: 70%; margin: 0 auto;\"> <a href=\"{button_url}\" style=\"font-size: 16px;font-weight: 700; padding: 15px 32px; border-radius: 50px; background: #2b8768; text-decoration: none; color: #ffffff; border: none;\">Accept Invitation</a> </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; margin: 0 auto; width: 70%;\">We can’t wait for you to see how simple invoicing can be!</p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 30px; margin: 0 auto; width: 70%;\">Best,</p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 10px; margin: 0 auto; width: 70%;\">The {app_name} Team</p>",
  },
  {
    type: "subscriber_register",
    subject: "You're Subscribed! Welcome to the Community",
    defaultContent: "<p class=\"logo\" style=\"text-align: center; width: 70%;\"><img width=\"auto\" height=\"72px\" src=\"{app_logo}\" alt=\"Logo\"/></p> <p style=\"color: #4F5867; font-size: 15px; padding-top: 20px; margin: 0 auto; width: 70%;\"> Hey, <span style=\"color: #2b8768; font-size: 20px;\">{receiver_name}</span> </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 30px; margin: 0 auto; width: 70%;\"> Thanks for signing up! You're now subscribed and will be the first to know about our latest updates, exclusive content, and special offers. </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 20px; margin: 0 auto; width: 70%;\"> We’re excited to have you on board! </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 20px; margin: 0 auto; width: 70%;\"> Your Login Information: </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 20px; margin: 0 auto; width: 70%;\"> <b>Email: {email}</b> </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 20px; margin: 0 auto; width: 70%;\"> <b>Password: {password}</b> </p> <p style=\"text-align: center; padding-top: 50px; padding-bottom: 50px; width: 70%; margin: 0 auto;\"> <a href=\"{button_url}\" style=\"font-size: 16px;font-weight: 700; padding: 15px 32px; border-radius: 50px; background: #2b8768; text-decoration: none; color: #ffffff; border: none;\">Visit Site</a> </p> <p style=\"width: 70%; margin: 0 auto; color: #4F5867; font-size: 15px; padding-top: 30px;\">Best,</p> <p style=\"width: 70%; margin: 0 auto; color: #4F5867; font-size: 15px; padding-top: 10px;\">{app_name} Team</p>",
  },
  {
    type: "account_has_been_deleted",
    subject: "Your {app_name} Account Has Been Deleted",
    defaultContent: "<p class=\"logo\" style=\"text-align: center; width: 70%;\"><img width=\"auto\" height=\"72px\" src=\"{app_logo}\" alt=\"Logo\"/></p> <p style=\"color: #4F5867; font-size: 15px; padding-top: 20px; margin: 0 auto; width: 70%;\"> Hey, <span style=\"color: #2b8768; font-size: 20px;\">John Doe</span> </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 30px; margin: 0 auto; width: 70%;\"> This is to confirm that your <strong>{app_name}</strong> account has been successfully deleted. We're sorry to see you go. </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 20px; margin: 0 auto; width: 70%;\"> If this was a mistake or you change your mind, you can easily sign up again at any time. </p> <p style=\"text-align: center; padding-top: 50px; padding-bottom: 50px; width: 70%; margin: 0 auto;\"> <a href=\"{button_url}\" style=\"font-size: 16px; font-weight: 700; padding: 15px 32px; border-radius: 50px; background: #2b8768; text-decoration: none; color: #ffffff; border: none;\">Create a New Account</a> </p> <p style=\"width: 70%; margin: 0 auto; color: #4F5867; font-size: 15px; padding-top: 30px;\">Best,</p> <p style=\"width: 70%; margin: 0 auto; color: #4F5867; font-size: 15px; padding-top: 10px;\">{app_name} Team</p>",
  },
  {
    type: "invoice_sending_attachment",
    subject: "Invoice {invoice_number} – Due on {due_date}",
    defaultContent: "<p class=\"logo\" style=\"text-align: center; width: 70%;\"><img width=\"auto\" height=\"72px\" src=\"{app_logo}\" alt=\"Logo\"/></p> <p style=\"color: #4F5867; font-size: 15px; padding-top: 20px; margin: 0 auto; width: 70%;\"> Hey, <span style=\"color: #2b8768; font-size: 20px;\">{receiver_name}</span> </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 30px; margin: 0 auto; width: 70%;\"> Hope you’re doing well! Attached is your invoice for recent services/products provided. </p> <p style=\"color: #2b8768; font-size: 15px; padding-top: 30px; font-weight: 500; margin: 0 auto; width: 70%;\"> Invoice Details: </p> <p style=\"display: flex; justify-content: space-between; flex-wrap: wrap; margin: 0 auto; width: 70%;\"> <span style=\"color: #4F5867; font-size: 15px; padding-top: 30px; font-weight: 400; float:left\"> Invoice Number: {invoice_number} </span> <span style=\"color: #4F5867; font-size: 15px; padding-top: 30px; padding-right: 10px; font-weight: 400; float:right\"> Due Date: {due_date} </span> </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 30px; margin: 0 auto; width: 70%; clear:both\"> We appreciate your prompt attention to this. If you have any questions or need adjustments, just let us know! </p> <p style=\"width: 70%; margin: 0 auto; color: #4F5867; font-size: 15px; padding-top: 30px;\">Best,</p> <p style=\"width: 70%; margin: 0 auto; color: #4F5867; font-size: 15px; padding-top: 10px;\">{app_name} Team</p>",
  },
  {
    type: "subscriber_billing_information",
    subject: "Billing Information – {billing_month}",
    defaultContent: "<p class=\"logo\" style=\"text-align: center; width: 70%;\"><img width=\"auto\" height=\"72px\" src=\"{app_logo}\" alt=\"Logo\"/></p> <p style=\"color: #4F5867; font-size: 15px; padding-top: 20px; margin: 0 auto; width: 70%;\"> Hello <span style=\"color: #2b8768; font-size: 20px;\">{subscriber_name}</span>, </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 30px; margin: 0 auto; width: 70%;\"> Here's your billing summary for <strong>{billing_month}</strong>. Thank you for being a valued subscriber. </p> <p style=\"color: #2b8768; font-size: 15px; padding-top: 30px; font-weight: 500; margin: 0 auto; width: 70%;\"> Billing Summary: </p> <p style=\"display: flex; justify-content: space-between; flex-wrap: wrap; margin: 0 auto; width: 70%;\"> <span style=\"color: #4F5867; font-size: 15px; padding-top: 30px; font-weight: 400; float:left\"> Plan: {subscription_plan} </span> <span style=\"color: #4F5867; font-size: 15px; padding-top: 30px; font-weight: 400; float:right\"> Amount: {billing_amount} </span> </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 30px; margin: 0 auto; width: 70%; clear:both\"> For your records, a copy of this billing summary is attached. If you have any questions, feel free to reach out. </p> <p style=\"width: 70%; margin: 0 auto; color: #4F5867; font-size: 15px; padding-top: 30px;\">Best,</p> <p style=\"width: 70%; margin: 0 auto; color: #4F5867; font-size: 15px; padding-top: 10px;\">{app_name} Team</p>",
  },
  {
    type: "payment_received",
    subject: "Payment Confirmation – Thank You!",
    defaultContent: "<p class=\"logo\" style=\"text-align: center; width: 70%;\"><img width=\"auto\" height=\"72px\" src=\"{app_logo}\" alt=\"Logo\"/></p> <p style=\"color: #4F5867; font-size: 15px; padding-top: 20px; margin: 0 auto; width: 70%;\"> Hey, <span style=\"color: #2b8768; font-size: 20px;\">{receiver_name}</span> </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 30px; margin: 0 auto; width: 70%;\"> We're happy to confirm that we’ve received your payment for invoice <strong>{invoice_number}</strong>. Thank you for your prompt payment! </p> <p style=\"color: #2b8768; font-size: 15px; padding-top: 30px; font-weight: 500; margin: 0 auto; width: 70%;\"> Payment Summary: </p> <p style=\"display: flex; justify-content: space-between; flex-wrap: wrap; margin: 0 auto; width: 70%;\"> <span style=\"color: #4F5867; font-size: 15px; padding-top: 30px; font-weight: 400; float:left\"> Invoice Number: {invoice_number} </span> <span style=\"color: #4F5867; font-size: 15px; padding-top: 30px; font-weight: 400; float:right\"> Paid On: {payment_date} </span> </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 30px; margin: 0 auto; width: 70%; clear:both\"> If you need a copy of your paid invoice or have any further questions, feel free to get in touch. We're always here to help! </p> <p style=\"width: 70%; margin: 0 auto; color: #4F5867; font-size: 15px; padding-top: 30px;\">Best,</p> <p style=\"width: 70%; margin: 0 auto; color: #4F5867; font-size: 15px; padding-top: 10px;\">{app_name} Team</p>",
  },
  {
    type: "estimate_sending_attachment",
    subject: "Estimate {estimate_number} – Ready for Review",
    defaultContent: "<p class=\"logo\" style=\"text-align: center; width: 70%;\"><img width=\"auto\" height=\"72px\" src=\"{app_logo}\" alt=\"Logo\"/></p> <p style=\"color: #4F5867; font-size: 15px; padding-top: 20px; margin: 0 auto; width: 70%;\"> Hey, <span style=\"color: #2b8768; font-size: 20px;\">{receiver_name}</span> </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 30px; margin: 0 auto; width: 70%;\"> Hope you’re doing well! Attached is your invoice for recent services/products provided. </p> <p style=\"color: #2b8768; font-size: 15px; padding-top: 30px; font-weight: 500; margin: 0 auto; width: 70%;\"> Estimate Summary: </p> <p style=\"display: flex; justify-content: space-between; flex-wrap: wrap; margin: 0 auto; width: 70%;\"> <span style=\"color: #4F5867; font-size: 15px; padding-top: 30px; font-weight: 400; float:left\"> Estimate: {estimate_number} </span> <span style=\"color: #4F5867; font-size: 15px; padding-top: 30px; font-weight: 400; float:right\"> Date: {estimate_date} </span> </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 30px; margin: 0 auto; width: 70%; clear:both\"> Please review the attached estimate and let us know if everything looks good or if you have any questions. We're here to assist! </p> <p style=\"width: 70%; margin: 0 auto; color: #4F5867; font-size: 15px; padding-top: 30px;\">Best,</p> <p style=\"width: 70%; margin: 0 auto; color: #4F5867; font-size: 15px; padding-top: 10px;\">{app_name} Team</p>",
  },
  {
    type: "forget_password",
    subject: "Reset Your Password Request",
    defaultContent: "<p class=\"logo\" style=\"text-align: center; width: 70%;\"> <img width=\"auto\" height=\"72px\" src=\"{app_logo}\" alt=\"Logo\"/> </p> <p style=\"color: #4F5867; font-size: 15px; padding-top: 20px; margin: 0 auto; width: 70%;\"> Hello, <span style=\"color: #2b8768; font-size: 20px;\">{receiver_name}</span> </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 30px; margin: 0 auto; width: 70%;\"> We received a request to reset your password. Click the button below to choose a new password. </p> <p style=\"text-align: center; padding-top: 40px; padding-bottom: 40px; width: 70%; margin: 0 auto;\"> <a href=\"{button_url}\" style=\"font-size: 16px; font-weight: 700; padding: 15px 32px; border-radius: 50px; background: #2b8768; text-decoration: none; color: #ffffff; border: none;\">Reset Password</a> </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 10px; margin: 0 auto; width: 70%;\"> If you didn't request a password reset, please ignore this email. Your current password will remain unchanged. </p> <p style=\"width: 70%; margin: 0 auto; color: #4F5867; font-size: 15px; padding-top: 30px;\">Best,</p> <p style=\"width: 70%; margin: 0 auto; color: #4F5867; font-size: 15px; padding-top: 10px;\">{app_name} Team</p>",
  },
  {
    type: "subscriber_expired_reminder",
    subject: "Your Subscription Has Expired – Renew to Stay Connected",
    defaultContent: "<p class=\"logo\" style=\"text-align: center; width: 70%;\"><img width=\"auto\" height=\"72px\" src=\"{app_logo}\" alt=\"Logo\"/></p> <p style=\"color: #4F5867; font-size: 15px; padding-top: 20px; margin: 0 auto; width: 70%;\"> Hi <span style=\"color: #2b8768; font-size: 20px;\">{subscriber_name}</span>, </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 30px; margin: 0 auto; width: 70%;\"> We noticed that your subscription expired on <strong>{expired_date}</strong>. We’d hate to see you miss out on the benefits you’ve been enjoying. </p> <p style=\"color: #2b8768; font-size: 15px; padding-top: 30px; font-weight: 500; margin: 0 auto; width: 70%;\"> Subscription Details: </p> <p style=\"display: flex; justify-content: space-between; flex-wrap: wrap; margin: 0 auto; width: 70%;\"> <span style=\"color: #4F5867; font-size: 15px; padding-top: 30px; font-weight: 400; float:left\"> Plan: {subscription_plan} </span> <span style=\"color: #4F5867; font-size: 15px; padding-top: 30px; font-weight: 400; float:right\"> Expired On: {expired_date} </span> </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 30px; margin: 0 auto; width: 70%; clear:both\"> To continue enjoying uninterrupted service, please renew your subscription today. </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 20px; margin: 0 auto; width: 70%;\"> Need help or have questions? We’re just a message away. </p> <p style=\"width: 70%; margin: 0 auto; color: #4F5867; font-size: 15px; padding-top: 30px;\">Best,</p> <p style=\"width: 70%; margin: 0 auto; color: #4F5867; font-size: 15px; padding-top: 10px;\">{app_name} Team</p>",
  },
  {
    type: "password_change_confirmation",
    subject: "Password Changed Successfully",
    defaultContent: "<p class=\"logo\" style=\"text-align: center; width: 70%;\"> <img width=\"auto\" height=\"72px\" src=\"{app_logo}\" alt=\"Logo\"/> </p> <p style=\"color: #4F5867; font-size: 15px; padding-top: 20px; margin: 0 auto; width: 70%;\"> Hello <span style=\"color: #2b8768; font-size: 20px;\">{receiver_name}</span>, </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 20px; margin: 0 auto; width: 70%;\"> We wanted to let you know that your password has been changed successfully. You don’t need to do anything else if you made this change. </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 20px; margin: 0 auto; width: 70%;\"> If you didn’t change your password, please reset it immediately or contact our support team. </p> <p style=\"text-align: center; padding-top: 40px; padding-bottom: 40px; width: 70%; margin: 0 auto;\"> <a href=\"{button_url}\" style=\"font-size: 16px; font-weight: 700; padding: 15px 32px; border-radius: 50px; background: #2b8768; text-decoration: none; color: #ffffff; border: none;\">Contact Support</a> </p> <p style=\"width: 70%; margin: 0 auto; color: #4F5867; font-size: 15px; padding-top: 30px;\">Best,</p> <p style=\"width: 70%; margin: 0 auto; color: #4F5867; font-size: 15px; padding-top: 10px;\">{app_name} Team</p>",
  },
  {
    type: "user_joined",
    subject: "Welcome to {app_name} – Let’s Get Started!",
    defaultContent: "<p class=\"logo\" style=\"text-align: center; width: 70%;\"> <img width=\"auto\" height=\"72px\" src=\"{app_logo}\" alt=\"Logo\"/> </p> <p style=\"color: #4F5867; font-size: 15px; padding-top: 20px; margin: 0 auto; width: 70%;\"> Hello <span style=\"color: #2b8768; font-size: 20px;\">{receiver_name}</span>, </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 20px; margin: 0 auto; width: 70%;\"> Welcome to <strong>{app_name}</strong>! We’re excited to have you on board. Your account has been successfully created and you can now start exploring all the features available to you. </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 20px; margin: 0 auto; width: 70%;\"> Click the button below to log in and get started. </p> <p style=\"text-align: center; padding-top: 40px; padding-bottom: 40px; width: 70%; margin: 0 auto;\"> <a href=\"{button_url}\" style=\"font-size: 16px; font-weight: 700; padding: 15px 32px; border-radius: 50px; background: #2b8768; text-decoration: none; color: #ffffff; border: none;\">Log In</a> </p> <p style=\"width: 70%; margin: 0 auto; color: #4F5867; font-size: 15px; padding-top: 30px;\">Best,</p> <p style=\"width: 70%; margin: 0 auto; color: #4F5867; font-size: 15px; padding-top: 10px;\">{app_name} Team</p>",
  },
  {
    type: "confirmation_of_account_deletion_request",
    subject: "Confirmation of Account Deletion Request",
    defaultContent: "<p class=\"logo\" style=\"text-align: center; width: 70%;\"> <img width=\"auto\" height=\"72px\" src=\"{app_logo}\" alt=\"Logo\"/> </p> <p style=\"color: #4F5867; font-size: 15px; padding-top: 20px; margin: 0 auto; width: 70%;\"> Hello <span style=\"color: #2b8768; font-size: 20px;\">{receiver_name}</span>, </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 20px; margin: 0 auto; width: 70%;\"> We’ve received your request to delete your account from <strong>{app_name}</strong>. We're sorry to see you go! </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 20px; margin: 0 auto; width: 70%;\"> Please confirm this request by clicking the button below. Once confirmed, your account and associated data will be permanently removed and cannot be recovered. </p> <p style=\"text-align: center; padding-top: 40px; padding-bottom: 40px; width: 70%; margin: 0 auto;\"> <a href=\"{button_url}\" style=\"font-size: 16px; font-weight: 700; padding: 15px 32px; border-radius: 50px; background: #2b8768; text-decoration: none; color: #ffffff; border: none;\">Confirm Deletion</a> </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; margin: 0 auto; width: 70%;\"> If you did not make this request or have changed your mind, no action is needed and your account will remain active. </p> <p style=\"width: 70%; margin: 0 auto; color: #4F5867; font-size: 15px; padding-top: 30px;\">Best,</p> <p style=\"width: 70%; margin: 0 auto; color: #4F5867; font-size: 15px; padding-top: 10px;\">{app_name} Team</p>",
  },
  {
    type: "customer_credential",
    subject: "Invitation for {app_name}",
    defaultContent: "<p class=\"logo\" style=\"text-align: center; width: 70%;\"><img width=\"auto\" height=\"72px\" src=\"{app_logo}\" alt=\"Logo\"/></p> <p style=\"color: #4F5867; font-size: 15px; padding-top: 20px; margin: 0 auto; width: 70%;\"> Hi, <span style=\"color: #2b8768; font-size: 20px;\">{receiver_name}</span> </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 30px; margin: 0 auto; width: 70%;\"> Welcome to <strong>{app_name}</strong>! We're excited to have you on board and want to ensure that your account is secure. </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 20px; margin: 0 auto; width: 70%;\"> Your Login Information: </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 10px; margin: 0 auto; width: 70%;\"> <b>Email: {email}</b> </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 10px; margin: 0 auto; width: 70%;\"> <b>Password: {password}</b> </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; padding-top: 30px; margin: 0 auto; width: 70%;\"> To complete your account setup, please click the button below. </p> <p style=\"text-align: center; padding-top: 50px; padding-bottom: 50px; width: 70%; margin: 0 auto;\"> <a href=\"{button_url}\" style=\"font-size: 16px; font-weight: 700; padding: 15px 32px; border-radius: 50px; background: #2b8768; text-decoration: none; color: #ffffff; border: none;\">Go to Your Account</a> </p> <p style=\"color: #4F5867; font-size: 15px; font-weight: 400; margin: 0 auto; width: 70%;\"> We look forward to providing you with a secure and seamless experience. </p> <p style=\"width: 70%; margin: 0 auto; color: #4F5867; font-size: 15px; padding-top: 30px;\">Best,</p> <p style=\"width: 70%; margin: 0 auto; color: #4F5867; font-size: 15px; padding-top: 10px;\">{app_name} Team</p>",
  },
] as const;
